PlayingWithPower/Oracle

objects/Oracle.js

Fixing !logging Issues spitting out 5 message

---

objects/Deck.js
objects/Oracle.js

Resolved, added indexes to the new mongoDB

Issue #300 involving indexing issues

---

objects/Deck.js
objects/Oracle.js

We released the #305 resolved issue to the dev server without proper testing. There was an issue with the duplicate user check creating nested arrays instead of just a regular array.
-Resolved by instead of pushing args to TempArr, we are looping thrgh args and pushing each individual element to TempArr

Issue #305 Changes after deployment to dev server

---

objects/Deck.js

Undefined length issues resolved with an added check of:
res!==undefined && ...

#307 Resolved, issue with length being undefined

---

Helpers/ManageReactionHelper.js
objects/Game.js
objects/Oracle.js

Added more descriptions to output logging messages:
-Winner (gains 30 points)
-Losers 1-3 (lose 10 points)
-@mentions users in the embed
-added a semi-colon where one needed to be added
-cleaned the output messages of logWinners/logLosers to better help out the final output message to the user
Closes #323

Updates to logging output messages

---

Helpers/FunctionHelper.js

!setendseason 12/12/2020 to
!setendseason 01/28/2020
Better highlights how to type in
closes #304

Changes typo on example usage

---

Helpers/DeckHelper.js
Helpers/ManageReactionHelper.js
objects/Oracle.js

-Security issues with DeckIDs being in !updatedeck removed, secondary system put in place
-downvoting now properly working
Resolution of #294

Security issues and downvote issues resolved

---

objects/User.js

Before, the query only checked if the last word was "Rogue", now it will check if the last 2 words are "|" and "Rogue".
Not a 100% perfect solution, but everytime we find some sort of edge/error case in this function we can add more complicated checks
closes #315

Upated a check in User.JS in the useDeck Function

---

main.js

Took out one of the name fields in the "SpellTableEmbed" highlighted at line 67 in main.js
closes #318

Removed first part of embed involving spelltable

---

main.js

Removed default condition in "Process Command" switch statement - Closes #316

---

objects/Season.js

Changed saving of new season start date to locale string format
Changed grabbing (displaying) of new season start date to reflect

Formatting changes to save/grabbing of season DB data

---

Helpers/FunctionHelper.js
objects/Oracle.js

-Mainly wording changes in !help
-Updated some footers in Oracle.js
-Updated the Admin Privs list to say "none" when the list is empty
closes #338

Changing words and a few minors pieces of functionality

---

Helpers/SeasonHelper.js
etc/env.js.dist
objects/Oracle.js

-!top was getting cut off by an arbitrary threshold
-I have updated the output of !top to resemble !deckstats, which is a much cleaner way to show data imo
-Emergency hot fix needed

!top getting cut off and displaying incorrect information

---

Helpers/FunctionHelper.js
objects/League.js
objects/Oracle.js

-Removed all instances of timeout from the code
-Changed some help messages to account for this

Timeout aspect of configs removed

---

objects/Oracle.js

-!top would fail when the threshold was so great that nobody would be listed on the embed for !top
-embed would become upset because it's empty
-added a check to make sure the information being added isn't blank

Resolving Development error on !top

---

objects/Oracle.js

-The for loop to display the top players would break instead of continuing, causing some users who have the required amount of games played, to not show up on the !top

The key difference between break and continue

---

Helpers/FunctionHelper.js
Helpers/SeasonHelper.js
etc/env.js.dist
objects/Oracle.js

Addresses #342 !top not displaying correct.

Release 1.0.2.1

---

objects/Oracle.js

-Issues with break and continue
-Issues with an iterator that was incorrect
-Changed the way the for loop counts how many users are being displayed on the top ten
-break and continue are different :)

Fixed production bug with !top

---

Helpers/SeasonHelper.js
objects/Oracle.js

#335:
-Pipes are now in !top, small restructuring, nothing major
-Added new error message to account for it
#336:
-Added functionality for !top | all
-Changed output for 'all', tells you winrate and wins instead of your score. Score is irrelevant across all seasons
Closes #335 and #336

#335 !top adding pipe

---

Helpers/DeckHelper.js
Helpers/ManageReactionHelper.js
objects/Deck.js
objects/Oracle.js

-Users can now add 5c and colorless decks
-Users can now filter by 5c, 5color, etc. and colorless and brown
closes #314

5c and Colorless Decks

---

Helpers/FunctionHelper.js

-Removed else
-Moved section where bot sends message to inside if statement (if command !== undefined)
closes #357

Removed bot sending message on !help <not defined>

---

objects/Oracle.js

-Bot will check if user is registered and then send a better output message (the username vs "Not Defined")
closes #366

Profile fixed

---

objects/Deck.js
objects/Oracle.js

-Deckstats output messages have been updated
-Fixed issues with confusing wordings
-The bot now first checks if what you're typing is a deck, then sends output messages based on whether or not it has any games or not this season
closes #274 
closes #362

Updating how Deckstats Works

---

Helpers/FunctionHelper.js
main.js
objects/League.js
objects/Oracle.js

-Changed "player threshold" to "minimum games"
-Changed "deck threshold" to "minimum decks"
closes #341

Updated names of Threshold

---

objects/Oracle.js

Small wording changes

---

objects/Oracle.js

-!log now accepts a lot more mistakes than it did before
-Typing something like.. !log @user @user q231lokjqwerlkwjflksdjflksdjf @user will now work
-TLDR: Spaces, random characters, etc in between @user tags is now accepted

Logging now more accepting

---

Helpers/ConfigHelper.js
Helpers/FunctionHelper.js
Schema/Config.js
objects/League.js
objects/Oracle.js

-Edits the number of users displayed in !top
-Fixed small bug with _admin in configs being set to a String and not an Array, would cause crashing
-Updated Schema
closes #349

Added new Threshold: Maximum Top

---

Helpers/FunctionHelper.js

Reverts PlayingWithPower/Oracle#372

Revert "Added new Threshold: Maximum Top"

---

Helpers/ConfigHelper.js
Helpers/FunctionHelper.js
Schema/Config.js
objects/League.js
objects/Oracle.js

#372 reimplemented, fixing some changes that never got pushed to live

Took changes from #372 PR and reimplemented them

---

objects/League.js
objects/Oracle.js

-!top was attempting to fetch undefined values
-added a check for !top to provide a default value when _top_threshold from configs is not present or undefined

Fixing issues from live

---

main.js
package-lock.json
package.json

closes #390 
-New library get-urls was added
-Extracts urls from a string.. outputs as Set
-Bot will now read in messages involving the spelltable prefix and will extract the url and add the "?spectate=true" modifier and spit it back out
-It will now only take the URL not any other text in a sentence

390 spelltable bug

---

objects/Oracle.js

Top command now has a "Games" section added. This counts the total games in the provided time frame
closes #393

Updated !top and its variants
